apiVersion: v1
kind: Pod
metadata:
  name: bucky
spec:
  volumes:
    - name: test-script
      emptyDir: {}
  containers:
  - name: bucky-core
    image: lifullsetg/bucky-core:latest
    tty: true
    volumeMounts:
    - name: test-script
      mountPath: /app
  - name: bucky-test-script
    image: bucky-test-script:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: test-script
      mountPath: /app
    command: ["/bin/sh"]
    args: ["-c", "cp -r /test-script/. /app/"]